import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./Components/Nav/Nav.css"; 
import "./Components/Main/Main.css"; 
import "./about/about.css"; 
import "./skills/skills.css"; 
import "./Components/CardSkills/CardSkills.css"; 
import "./projetos/projetos.css"

import Nav from "./Components/Nav/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="container-main">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}